language: java
# speed up travis with repo caching https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - $HOME/.m2

#using jobs instead
install: mvn install -Dgpg.skip=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B -V -Pquickrun,examples

jdk:
  - openjdk8
  - openjdk11

before_script:
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS
